spring:
  datasource:
    jdbcUrl: jdbc:mysql://localhost:3306/demo
    username: root
    password:
    driverClassName: com.mysql.jdbc.Driver

server:
  error:
    include-binding-errors: always
    include-message: always
